# Generated by Django 2.0.1 on 2018-01-14 21:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A custom field', max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('value', ckeditor.fields.RichTextField(help_text='The value of this field', max_length=20000)),
            ],
            options={
                'ordering': ['type__slug', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A custom field type', max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('name_plural', models.CharField(help_text='This type in plural, for presentation', max_length=255)),
                ('description', models.CharField(help_text='Describe this custom field type', max_length=255)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A wiki entry', max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('value', ckeditor.fields.RichTextField(blank=True, help_text='The value of this field', max_length=20000)),
                ('custom_fields', models.ManyToManyField(blank=True, help_text='The custom fields (if any), the order is the presentation order', to='wiki.CustomField')),
                ('custom_fields_presentation_order', models.ManyToManyField(blank=True, help_text='The custom field types (if any), the order is the presentation order', to='wiki.CustomFieldType')),
            ],
            options={
                'ordering': ['section__slug', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A wiki section/category', max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('description', models.CharField(help_text='Describe this wiki section', max_length=255)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='section',
            field=models.ForeignKey(help_text='The section to witch this entry belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.Section'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='type',
            field=models.ForeignKey(help_text='The type of this field', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.CustomFieldType'),
        ),
    ]
