# Generated by Django 2.0.1 on 2018-01-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfieldtype',
            options={},
        ),
    ]
