# Generated by Django 2.0.1 on 2018-01-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['section__slug', 'slug'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='A wiki section/category', max_length=200, unique=True),
        ),
    ]
