# Generated by Django 2.0.1 on 2018-01-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20180115_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldtype',
            name='description',
            field=models.TextField(help_text='Describe this custom field type', max_length=2500),
        ),
        migrations.AlterField(
            model_name='customfieldtype',
            name='name_plural',
            field=models.CharField(help_text='This type in plural, for wiki entry presentation', max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(help_text='Describe this wiki section', max_length=2500),
        ),
    ]
