# Generated by Django 2.0.1 on 2018-01-25 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20180125_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['type__slug', 'order_id']},
        ),
        migrations.AlterModelOptions(
            name='customfieldtype',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='customfield',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in wiki entry page'),
        ),
        migrations.AddField(
            model_name='customfieldtype',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in wiki entry page'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='custom_fields',
            field=models.ManyToManyField(blank=True, help_text="The custom fields (if any), The presentation order (that's determined by the order_id of the field) will be shown onthe right after saving", to='wiki.CustomField'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='custom_fields_presentation_order',
            field=models.ManyToManyField(blank=True, help_text="The custom field types (if any). The presentation order (that's determined by the order_id of the type) will be shown onthe right after saving", to='wiki.CustomFieldType'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, help_text='A list of users that marked this entry as their favorite, better leave untouched', to=settings.AUTH_USER_MODEL),
        ),
    ]
