# Generated by Django 2.0.1 on 2018-01-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20180115_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(help_text='A wiki entry', max_length=200, unique=True),
        ),
    ]
