# Generated by Django 2.0.1 on 2018-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20180125_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['section__slug', 'order_id'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in wiki section page'),
        ),
    ]
