# Generated by Django 2.0.1 on 2018-01-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20180124_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in wiki sections menu', unique=True),
        ),
    ]
