# Generated by Django 2.0.1 on 2018-01-25 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0006_auto_20180124_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='favorite_by',
            field=models.ManyToManyField(help_text='A list of users that marked this entry as their favorite', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
