# Generated by Django 2.0.1 on 2018-01-25 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_entry_favorite_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='favorite_by',
            field=models.ManyToManyField(help_text='A list of users that marked this entry as their favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
