language: python

# python version:
python:
  - "3.6"

# ask for database service:
services:
  - postgresql

# create local .env file from .travis.env:
before_install:
  - mv .travis.env .env

# install dependencies and coveralls:
install:
  - pip install -r requirements.txt
  - pip install coveralls

# set up database, make migrations, migrate, and create super user:
before_script:
  - psql -c "CREATE DATABASE devteamhub;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
  - echo "from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); User.objects.create_superuser('admin', 'admin@example.com', 'nimda')" | python manage.py shell

# run tests:
script:
  - python manage.py test

# coveralls for code coverage:
after_success:
  - coveralls