language: python

# python version:
python:
  - "3.6"

# ask for database service:
services:
  - postgresql

# create local .env file from .travis.env:
before_install:
  - mv .travis.env .env

# install dependencies and coveralls:
install:
  - pip install -r requirements.txt
  - pip install coveralls

# set up database, make migrations and migrate before tests:
before_script:
  - psql -c "CREATE DATABASE devteamhub;" -U devteamhubadmin
  - python manage.py makemigrations
  - python manage.py migrate

# create super user, and then tests on specific apps
script:
#  - echo "from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); User.objects.create_superuser('admin', 'admin@example.com', 'nimda')" | python manage.py shell
  - python manage.py test
#  - coverage run manage.py test

# run coveralls if tests were successful
after_success:
  - coveralls