# Generated by Django 2.0.1 on 2018-01-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Add tags that describe this article', to='news.Tag'),
        ),
    ]
