# Generated by Django 2.0.1 on 2018-01-12 20:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180111_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(help_text='Write the article here', max_length=20000),
        ),
    ]
