# Generated by Django 2.0.1 on 2018-01-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20180122_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(help_text='What kind of topics should be in this category?', max_length=1000),
        ),
    ]
