# Generated by Django 2.0.1 on 2018-01-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order_id', models.PositiveSmallIntegerField(default=0, help_text='Order for custom links drop-down menu', unique=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dev Team Hub', max_length=50)),
                ('current_release_version', models.CharField(default='0.0.1-SNAPSHOT', max_length=50)),
                ('current_release_notes', models.ForeignKey(help_text='Link to release notes article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Article')),
                ('custom_links', models.ManyToManyField(blank=True, help_text='Choose custom links', to='hub.CustomLink')),
            ],
            options={
                'verbose_name_plural': 'site config',
            },
        ),
    ]
