# Generated by Django 2.0.1 on 2018-01-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('order_id', models.PositiveSmallIntegerField(default=0, help_text='Order in custom links drop-down menu, relative to other custom links.')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dev Team Hub', max_length=50)),
                ('current_release_version', models.CharField(default='0.0.1-SNAPSHOT', max_length=50)),
                ('current_release_notes', models.ForeignKey(blank=True, help_text='Link to a release notes article that users can reach by clicking the current version button in the nav-bar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Article')),
                ('custom_links', models.ManyToManyField(blank=True, help_text='Choose custom links. The presentation order (that is determined by the order id of the custom links) will be shown on the right after saving.', to='hub.CustomLink')),
            ],
            options={
                'verbose_name_plural': 'site config',
            },
        ),
    ]
