# Generated by Django 2.0.1 on 2018-01-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dev Team Hub', max_length=50)),
                ('current_release_version', models.CharField(default='0.0.1-SNAPSHOT', max_length=50)),
                ('custom_links', models.ManyToManyField(blank=True, help_text='Choose custom links, order is important', to='hub.CustomLink')),
            ],
        ),
    ]
