# Generated by Django 2.0.1 on 2018-01-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customlink',
            options={},
        ),
    ]
