# Generated by Django 2.0.1 on 2018-01-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20180123_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customlink',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='customlink',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
