# Generated by Django 2.0.1 on 2018-01-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20180123_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlink',
            name='order_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
