# Generated by Django 2.0.1 on 2018-01-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20180123_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customlink',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='customlink',
            name='order_id',
        ),
    ]
