# Generated by Django 2.0.1 on 2018-01-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_auto_20180123_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlink',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order for custom links drop-down menu', unique=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='custom_links',
            field=models.ManyToManyField(blank=True, help_text='Choose custom links', to='hub.CustomLink'),
        ),
    ]
