# Generated by Django 2.0.1 on 2018-01-25 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_published'),
        ('hub', '0009_auto_20180123_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='current_release_release_notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Article'),
        ),
    ]
